# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colaboratory.

"""

!apt-get install tesseract-ocr
!pip install pytesseract

def read_text_from_img(img):
  return pytesseract.image_to_string(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))

import cv2
import pytesseract

read_text_from_img(cv2.imread('/content/sample_data/picture1.jpg'))
read_text_from_img(cv2.imread('/content/sample_data/picture2.png'))
read_text_from_img(cv2.imread('/content/sample_data/picture3.png'))
read_text_from_img(cv2.imread('/content/sample_data/picture4.jpg'))
read_text_from_img(cv2.imread('/content/sample_data/picture5.jpg'))

#'Noisyimage\nto test\nTesseract OCR\n\x0c'